name: spot_time
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  dio: ^5.9.0
  appwrite: ^17.1.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.5
  intl: ^0.20.2
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.4
  bloc: ^9.0.0
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0


flutter:
  uses-material-design: true

  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
